"""
ops_ingest/contracts/events.py
================================
Domain event contracts for OilOps-PredictiveCore.

These Pydantic models represent the domain events that flow between services
in the ingestion and prediction pipeline.  They are defined here in
``ops_ingest/contracts/`` because ``ops-ingest`` is the origin of the
pipeline; all downstream services (``ops-feature``, ``ops-models``,
``ops-explain``) consume these event types.

Design rationale (DA-04 from plan.md)
--------------------------------------
In Phase 1, inter-service communication is synchronous HTTP.  However, the
event contracts are defined as first-class Pydantic models **from the
start** so that Phase 2 migration to Kafka requires only adding serialisation
adapters, not redesigning the domain model.

Every event carries a ``trace_id`` field that propagates the distributed
trace identifier generated by ``ops-api``'s ``TracingMiddleware`` (TASK-021).
This satisfies the logging requirement from INIT-US-08 AC4 and CAT-07/CAT-08:
the same ``trace_id`` must appear in logs from ``ops-ingest``,
``ops-store``, ``ops-feature``, and ``ops-models`` for a given request.

Security note
-------------
All fields enforce ``min_length=1`` on string identifiers to prevent blank
values from silently propagating through the pipeline (OWASP input
validation guidance; consistent with the ``CanonicalReading`` schema in
``shared/schemas/canonical.py``).

Usage
-----
>>> from ops_ingest.contracts.events import (
...     IngestionCompletedEvent,
...     FeaturesComputedEvent,
...     PredictionEmittedEvent,
... )
>>> import uuid
>>> from datetime import datetime, timezone
>>> event = IngestionCompletedEvent(
...     trace_id="abc-123",
...     ingestion_id=uuid.uuid4(),
...     asset_ids=["PUMP-001"],
...     records_accepted=10,
...     records_rejected=0,
...     occurred_at=datetime.now(tz=timezone.utc),
... )
"""

from __future__ import annotations

import uuid
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field


class IngestionCompletedEvent(BaseModel):
    """Emitted by ``ops-ingest`` after a batch of telemetry has been
    normalised and persisted in ``ops-store``.

    Downstream consumers (``ops-feature``) use this event to know which
    assets have new raw readings available for feature computation.

    Attributes
    ----------
    trace_id:
        Distributed trace identifier propagated from the originating HTTP
        request.  Present in all log entries for this pipeline run.
    ingestion_id:
        UUID of the ingestion batch — maps to ``ingestion_batches.id`` in
        SQLite (plan.md § 4.1).
    asset_ids:
        Non-empty list of asset identifiers that received new readings in
        this batch.
    records_accepted:
        Count of readings successfully normalised and persisted.
    records_rejected:
        Count of readings rejected due to validation errors.
    occurred_at:
        Timestamp at which the event was created (UTC, timezone-aware).
    """

    model_config = {"populate_by_name": True}

    trace_id: Annotated[str, Field(min_length=1, max_length=64)] = Field(
        description="Distributed trace identifier propagated from the originating request.",
    )
    ingestion_id: uuid.UUID = Field(
        description="UUID of the ingestion batch (maps to ingestion_batches.id in SQLite).",
    )
    asset_ids: list[Annotated[str, Field(min_length=1, max_length=64)]] = Field(
        description="Non-empty list of asset identifiers that received new readings.",
    )
    records_accepted: int = Field(
        ge=0,
        description="Count of readings successfully normalised and persisted.",
    )
    records_rejected: int = Field(
        ge=0,
        description="Count of readings rejected due to validation errors.",
    )
    occurred_at: AwareDatetime = Field(
        description="Timestamp at which the event was created (UTC, timezone-aware).",
    )


class FeaturesComputedEvent(BaseModel):
    """Emitted by ``ops-feature`` after feature extraction has been
    completed for a given asset and time window.

    Downstream consumers (``ops-models``) use this event to know that a
    new feature vector is available for model inference.

    Attributes
    ----------
    trace_id:
        Distributed trace identifier propagated from the originating request.
    asset_id:
        Identifier of the asset for which features were computed.
    feature_record_id:
        UUID of the persisted feature record in DuckDB
        (maps to ``feature_records.id`` — plan.md § 4.2).
    feature_version:
        Version string of the feature pipeline that produced this record
        (e.g. ``"1.0.0"``).
    occurred_at:
        Timestamp at which the event was created (UTC, timezone-aware).
    """

    model_config = {"populate_by_name": True}

    trace_id: Annotated[str, Field(min_length=1, max_length=64)] = Field(
        description="Distributed trace identifier propagated from the originating request.",
    )
    asset_id: Annotated[str, Field(min_length=1, max_length=64)] = Field(
        description="Identifier of the asset for which features were computed.",
    )
    feature_record_id: uuid.UUID = Field(
        description="UUID of the persisted feature record (feature_records.id in DuckDB).",
    )
    feature_version: Annotated[str, Field(min_length=1, max_length=32)] = Field(
        description="Version of the feature pipeline that produced this record.",
    )
    occurred_at: AwareDatetime = Field(
        description="Timestamp at which the event was created (UTC, timezone-aware).",
    )


class PredictionEmittedEvent(BaseModel):
    """Emitted by ``ops-models`` after a prediction has been computed and
    persisted for a given asset.

    Downstream consumers (``ops-explain``) use this event to enqueue an
    asynchronous SHAP attribution computation (DA-03, RN-04).  The
    ``ops-api`` WebSocket manager also listens for this event to broadcast
    real-time predictions to connected clients (INIT-US-04).

    Attributes
    ----------
    trace_id:
        Distributed trace identifier propagated from the originating request.
    prediction_id:
        UUID of the persisted prediction record
        (maps to ``predictions.id`` in SQLite — plan.md § 4.3).
    asset_id:
        Identifier of the asset for which the prediction was made.
    asset_class:
        Class of the asset (e.g. ``"rotating_equipment"``).
    model_version:
        Version string of the model that generated the prediction
        (e.g. ``"vibration-autoencoder-v1"``).
    anomaly_score:
        Anomaly score in the range [0.0, 1.0].
    confidence_score:
        Confidence of the prediction in the range [0.0, 1.0].
    alert:
        ``True`` when ``anomaly_score`` exceeds the model's configured
        ``anomaly_threshold``.
    occurred_at:
        Timestamp at which the event was created (UTC, timezone-aware).
    """

    # ``protected_namespaces = ()`` suppresses the Pydantic warning for
    # ``model_version`` — "model_" is a Pydantic-reserved prefix by default.
    # We explicitly opt out because ``model_version`` is a domain field, not
    # a Pydantic configuration key.
    model_config = {"populate_by_name": True, "protected_namespaces": ()}

    trace_id: Annotated[str, Field(min_length=1, max_length=64)] = Field(
        description="Distributed trace identifier propagated from the originating request.",
    )
    prediction_id: uuid.UUID = Field(
        description="UUID of the persisted prediction record (predictions.id in SQLite).",
    )
    asset_id: Annotated[str, Field(min_length=1, max_length=64)] = Field(
        description="Identifier of the asset for which the prediction was made.",
    )
    asset_class: Annotated[str, Field(min_length=1, max_length=64)] = Field(
        description="Class of the asset (e.g. 'rotating_equipment').",
    )
    model_version: Annotated[str, Field(min_length=1, max_length=64)] = Field(
        description="Version string of the model that generated the prediction.",
    )
    anomaly_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Anomaly score in the range [0.0, 1.0].",
    )
    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence of the prediction in the range [0.0, 1.0].",
    )
    alert: bool = Field(
        description="True when anomaly_score exceeds the model's configured anomaly_threshold.",
    )
    occurred_at: AwareDatetime = Field(
        description="Timestamp at which the event was created (UTC, timezone-aware).",
    )
