"""
tests/test_advisory.py
========================
Integration tests for AdvisoryMiddleware (TASK-021).

Criteria verified (from tasks.md TASK-021):
  - Any response from the app has header ``X-Advisory-Only: true``.
  - The header is present on successful (2xx) responses.
  - The header is present on error (4xx/5xx) responses generated by FastAPI.
"""

from __future__ import annotations

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from ops_api.app.middleware.advisory import AdvisoryMiddleware


# ---------------------------------------------------------------------------
# Fixture: minimal FastAPI app with AdvisoryMiddleware registered
# ---------------------------------------------------------------------------


@pytest.fixture()
def advisory_app() -> FastAPI:
    """Return a minimal FastAPI app that has AdvisoryMiddleware + exception handler.

    The exception handler is required because Starlette's ServerErrorMiddleware
    bypasses ASGI middlewares for unhandled exceptions; the handler closes that
    gap and ensures the advisory header is present on 500 responses too.
    """
    from fastapi import Request
    from fastapi.responses import JSONResponse

    _app = FastAPI()
    _app.add_middleware(AdvisoryMiddleware)

    @_app.exception_handler(Exception)
    async def _global_exc(request: Request, exc: Exception) -> JSONResponse:
        return JSONResponse(
            status_code=500,
            content={"detail": "Internal server error"},
            headers={"X-Advisory-Only": "true"},
        )

    @_app.get("/ok")
    async def _ok() -> dict[str, str]:
        return {"status": "ok"}

    @_app.get("/fail")
    async def _fail() -> None:
        raise ValueError("deliberate error")

    return _app


@pytest.fixture()
def client(advisory_app: FastAPI) -> TestClient:
    return TestClient(advisory_app, raise_server_exceptions=False)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestAdvisoryMiddleware:
    """Verify X-Advisory-Only: true is injected in all response types."""

    def test_header_present_on_200_response(self, client: TestClient) -> None:
        """Successful response must carry X-Advisory-Only: true."""
        response = client.get("/ok")
        assert response.status_code == 200
        assert response.headers.get("x-advisory-only") == "true"

    def test_header_value_is_lowercase_true(self, client: TestClient) -> None:
        """Header value must be the string 'true' (not 'True' or '1')."""
        response = client.get("/ok")
        assert response.headers["x-advisory-only"] == "true"

    def test_header_present_on_404_response(self, client: TestClient) -> None:
        """FastAPI 404 response (unknown route) must also carry the header."""
        response = client.get("/nonexistent-route-xyz")
        assert response.status_code == 404
        assert response.headers.get("x-advisory-only") == "true"

    def test_header_present_on_500_response(self, client: TestClient) -> None:
        """Server-error response must carry the header."""
        response = client.get("/fail")
        assert response.status_code == 500
        assert response.headers.get("x-advisory-only") == "true"

    def test_main_app_has_advisory_header(self) -> None:
        """The production ops-api app (main.py) must inject the header."""
        from ops_api.app.main import app as prod_app

        with TestClient(prod_app) as prod_client:
            response = prod_client.get("/")
            assert response.headers.get("x-advisory-only") == "true"

    def test_main_app_root_contains_advisory_message(self) -> None:
        """Root endpoint must include an advisory warning in its payload."""
        from ops_api.app.main import app as prod_app

        with TestClient(prod_app) as prod_client:
            response = prod_client.get("/")
            assert response.status_code == 200
            body = response.json()
            assert "advisory" in body
            assert "advisory" in body["advisory"].lower() or "warning" in body["advisory"].lower()
